/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.petshop;

/**
 *
 * @author sergi
 */
public class pet extends javax.swing.JFrame {
    int Animal, Categoria;
    

    /**
     * Creates new form pet
     */
    public pet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comAni = new javax.swing.JComboBox<>();
        comCat = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ibiprecio = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Pet Shop");

        comAni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perros", "Serpientes", "Conejos", "Peces" }));
        comAni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comAniMouseClicked(evt);
            }
        });
        comAni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comAniActionPerformed(evt);
            }
        });

        comCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comCatMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setText("Animal ");

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel3.setText("Categoria ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Precio:");

        ibiprecio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ibiprecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ibiprecio.setText("0.0");

        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jButton1.setText("Comprar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comAni, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(comCat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ibiprecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comAni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(ibiprecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comAniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comAniMouseClicked
Animal=comAni.getSelectedIndex();

if (Animal==0){
    comCat.removeAllItems();
    comCat.addItem("Pastor Aleman");
    comCat.addItem("Chihuahua");
    comCat.addItem("Pug");
    comCat.addItem("Labrador");
    comCat.addItem("Bulldog");
    
}

if (Animal==1){
    comCat.removeAllItems();
    comCat.addItem("Piton de India");
    comCat.addItem("Serpiente de Maiz");
    comCat.addItem("Serpiente de leche");
    comCat.addItem("Serpiente Ratonera");
    comCat.addItem("Anaconda");
    
}

if (Animal==2){
    comCat.removeAllItems();
    comCat.addItem("Belgian Here");
    comCat.addItem("Mini Rex");
    comCat.addItem("Florida White");
    comCat.addItem("Mini Lop");
    comCat.addItem("Englesh Sport");
    
}
if (Animal==3){
    comCat.removeAllItems();
    comCat.addItem("Pez Guppy");
    comCat.addItem("Pez Dorado");
    comCat.addItem("Pez Platy");
    comCat.addItem("Pez Cebra");
    comCat.addItem("Pez Betta");
    comCat.addItem("Pez Angel");
    comCat.addItem("Pez Disco");
    comCat.addItem("Pez Xhipo");
    
}
    }//GEN-LAST:event_comAniMouseClicked

    private void comCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comCatMouseClicked
Categoria=comCat.getSelectedIndex();
if ((Animal==0)&&(Categoria==0)){
    ibiprecio.setText("$15,000");
}
if ((Animal==0)&&(Categoria==1)){
    ibiprecio.setText("$11,000");
}
if ((Animal==0)&&(Categoria==2)){
    ibiprecio.setText("$5,000");
}
if ((Animal==0)&&(Categoria==3)){
    ibiprecio.setText("$4,000");
}
if ((Animal==0)&&(Categoria==4)){
    ibiprecio.setText("$13,000");
}
//serpientes
if ((Animal==1)&&(Categoria==0)){
    ibiprecio.setText("$30,000");
}
if ((Animal==1)&&(Categoria==1)){
    ibiprecio.setText("$35,000");
}
if ((Animal==1)&&(Categoria==2)){
    ibiprecio.setText("$15,000");
}
if ((Animal==1)&&(Categoria==3)){
    ibiprecio.setText("$27,000");
}
if ((Animal==1)&&(Categoria==4)){
    ibiprecio.setText("$23,800");
}
//conejos 
if ((Animal==2)&&(Categoria==0)){
    ibiprecio.setText("$8,000");
}
if ((Animal==2)&&(Categoria==1)){
    ibiprecio.setText("$3,000");
}
if ((Animal==2)&&(Categoria==2)){
    ibiprecio.setText("$5,000");
}
if ((Animal==2)&&(Categoria==3)){
    ibiprecio.setText("$11,000");
}
if ((Animal==2)&&(Categoria==4)){
    ibiprecio.setText("$9,000");
}
//peces 
if ((Animal==3)&&(Categoria==0)){
    ibiprecio.setText("$1,000");
}
if ((Animal==3)&&(Categoria==1)){
    ibiprecio.setText("2,000");
}
if ((Animal==3)&&(Categoria==2)){
    ibiprecio.setText("$400");
}
if ((Animal==3)&&(Categoria==3)){
    ibiprecio.setText("$550");
}
if ((Animal==3)&&(Categoria==4)){
    ibiprecio.setText("$850");
}
if ((Animal==3)&&(Categoria==5)){
    ibiprecio.setText("$400");
}
  if ((Animal==3)&&(Categoria==6)){
    ibiprecio.setText("900");
}
  if ((Animal==3)&&(Categoria==7)){
    ibiprecio.setText("$120");
}
  
    }//GEN-LAST:event_comCatMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comAniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comAniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comAniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comAni;
    private javax.swing.JComboBox<String> comCat;
    private javax.swing.JLabel ibiprecio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
